### PR TITLE
Mc1.14 porting2: Snapshot for review and sync.

### PR DESCRIPTION
**Pull request by stfwi**
- The Block should now about to be ok.
- TileEntity WIP, most methods existing in 1.12 re-renabled or ported accordingly.
- Should be possible to load Writable Books into the processor now.
- Added comments (marked with todo) for review.

### CODE REVIEW

**Comment by stfwi** [comment]
Travis seems to have an issue installing oraclejdk8, (says 9 to 15 valid). No idea if another kind of travis.yml spec is needed to get this flying.

**Comment by frodare** [comment]
Yeah, I am not too worried about the travis error. I will need to look into it soon to see what's up.  Did you want me to leave this PR open while you are working on it, or would you prefer me to keep merging them?

**Comment by stfwi** [comment]
I think we can leave it open, I may have a few hours today ;)

**Comment by stfwi** [comment]
Ok, things were progressing a bit. If we ignore the code book the basic functionality all ported I think.
There is one problem left with the neighbor notification of the redstone outputs, and ADC is not tested yet.

**Comment by stfwi** [comment]
Okay, I am stuck with the redstone updates of the adjacent blocks (have some weird changes around the `updateOutputs()`. Probably this PR one could be reviewed and pulled in as snapshot.
Do you have experience with 1.14 and redstone?

**Comment by frodare** [comment]
I haven't done that much modding since 1.10, and very little redstone. I can take a look though.  I do remember having a tough time getting the redstone signals to work when I was building the first version.  My schedule is pretty tight right now, not sure I will have any time work on it in the new few days but I will at least get it merged in.

**Comment by stfwi** [comment]
Ok, let's merge it, maybe someone else has also an idea where the problem is. I have also asked in the modder channels for advice. It's not much missing to a first alpha I think.

**Pull request merged**
