### PR TITLE
Code book implemented, Server-client-sync fixed.

### PR DESCRIPTION
**Pull request by stfwi**
Vacation-5h-hacking-marathon ;) I hope I did not miss a cleanup change you made in the last commit. I think the mod it's almost at alpha-release state.

### CODE REVIEW

**Comment by stfwi** [comment]
The Code book GUI proposal looks like this:


Have added some additional functions like pageup/down and mouse scrolling pages. GUI stuff can actually be a fun thing.

**Comment by stfwi** [comment]
Tool tip proposal format screenshot:

**Comment by frodare** [comment]
Nice!  Nope, I will wait to make any changes until you finish to avoid unneeded conflicts.  I do want to change the icons back to the lower res ones to better mimic the mojang's style.  And I will run a code formatter.  Both are minor and can wait.  

That code book looks great!

**Comment by stfwi** [comment]
Perfect that. I guess I'll have a closer testing look tomorrow if my time allows it and maybe check for some minor tweaks in the code book GUI. E.g. not sure yet if I am happy with the style of the close-button I added - stuff like that.

**Comment by stfwi** [comment]
Okay, this is how far I could push it, if there are questions etc just ping me. Cheers -

**Pull request merged**
